### PR TITLE
Adding tests

### PR DESCRIPTION
**Pull request by capellini**
Adding tests using mocha, chai, and sinon.  Using nyc for test coverage.

### CODE REVIEW

**Comment by capellini** [comment]
I saw this in an open issue:

>  more interested in a PR that sets up tests right now...

and thought that I would lend a hand.

**Comment by kapouer** [comment]
That's really cool ! I see there's a failing test though:
```
  1) rewrite tests
       using the wildcard * to soak up several segments
         rewrites if path matches:

      AssertionError: expected '/js/vendor/jquery.js' to equal '/public/assets/js/vendor/jquery.js'
      + expected - actual

      -/js/vendor/jquery.js
      +/public/assets/js/vendor/jquery.js

 ``

**Comment by capellini** [comment]
> I see there's a failing test though

Interesting.  It works on my machine (I'm currently using v8.11.3).  What version of node are you using?  I can try and use that version and see if I can track down why the test is failing.

**Comment by kapouer** [comment]
nodejs 10.15 but oh ! i removed node_modules and reinstalled again and now all tests pass.

**Comment by capellini** [comment]
Excellent!

**Pull request merged**
