### PR TITLE
Implement basic Query String Append for query merging

### LINKED ISSUE #2: Merge queries like with mod_rewrite's QSA flag
Hi there, 

Is there a way to merge queries like Apache's mod_rewrite QSA flag (query string append)?

https://httpd.apache.org/docs/2.4/rewrite/flags.html#flag_qsa

cheers

### PR DESCRIPTION
**Pull request by santillaner**
Hi there, 

This PR resolves #2 implementing a basic Query String Append inspired in httpd's mod_rewrite. It is backwards compatible, since it only kicks-in if an optional flag array is passed that includes "QSA". 

Sample usage would be like:

```
app.use(rewrite("/mypath/:to_query/*", "/newpath/$2?param1=$1&param2=whatever", ["QSA"]))
```
I've used mod_rewrite's flag array concept, so that more flags could easily be added in the future.

Cheers!

### CODE REVIEW

**Comment by kapouer** [comment]
Thank you, as i said i really need to think this through and add a test suite before changing anything. Also i'm going on vacation... so i might not do anything for a while.

**Comment by santillaner** [comment]
No worries, take your time. It's a pretty straightforward change, though. 

I'll be working from my fork anyway, at least for the moment. Just thought it's always nice to give back. Let me know if you need some help when you get your hands on this. 

Cheers!

**Comment by kapouer** [comment]
Hey there's a test suite now thanks to @capellini

**Comment by kapouer** [comment]
@santillaner i'm closing this because of inactivity. Feel free to open a new issue if needed.

**Pull request closed without merging**
